[workspace]
members = ["ast", "inko", "compiler", "rt", "location"]
resolver = "2"

[workspace.package]
version = "0.19.0" # VERSION
rust-version = "1.84"

[profile.release]
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = true
