[package]
name = "inko"
version = "0.12.0" # VERSION
authors = ["Yorick Peterse <yorick@yorickpeterse.com>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
getopts = "^0.2"
compiler = { path = "../compiler" }
