site_name: The Inko manual
site_description: The Inko programming language manual
site_author: The Inko programming language developers
site_url: https://docs.inko-lang.org/manual
docs_dir: source
site_dir: build
use_directory_urls: true
repo_url: https://github.com/inko-lang/inko
repo_name: Inko
edit_uri: -/tree/master/docs
theme:
  name: material
  favicon: images/favicon.ico
  logo: images/logo.png
  font: false
  features:
    - navigation.tabs
  palette:
    primary: white
    accent: blue
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.caret
nav:
  - Home: index.md
  - Getting started:
    - getting-started/installation.md
    - getting-started/editors.md
    - getting-started/cli.md
    - getting-started/ivm.md
    - getting-started/hello-world.md
    - getting-started/memory-management.md
    - getting-started/types.md
    - getting-started/variables.md
    - getting-started/error-handling.md
    - getting-started/pattern-matching.md
    - getting-started/concurrency.md
    - getting-started/modules.md
  - Reference:
    - guides/syntax.md
    - guides/style-guide.md
    - guides/structure.md
    - guides/testing.md
    - guides/ffi.md
    - guides/operators.md
    - guides/scaling.md
    - guides/contributing.md
  - Internals:
    - internals/compiler.md
    - internals/runtime.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inko-lang/inko
      name: View on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/seeURxHxCb
      name: Chat on Discord
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/inko
      name: Join the /r/inko subreddit
  version:
    provider: mike
    default: latest
