---
name: Tests
on: push
env:
  CARGO_HOME: ${{ github.workspace }}/.cargo

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  # Clippy uses a specific version as its lints change over time, which could
  # result in random unrelated CI failures. We'll bump this version every now
  # and then when needed.
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.62
        with:
          components: 'clippy'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cargo
            target
          key: ${{ runner.os }}-alpine
      - run: 'cargo clippy -- -D warnings'

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: 'rustfmt'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cargo
            target
          key: ${{ runner.os }}-alpine
      - run: 'cargo fmt --all --check'

  gitlint:
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/inko-lang/containers:python'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - run: git config --global --add safe.directory $PWD
      - run: gitlint --commits "HEAD~9..HEAD"

  compiler:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        version:
          - '1.62'
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cargo
            target
          key: ${{ runner.os }}-stable
      - name: Running tests
        run: cargo test

  std:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    needs:
      - compiler
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.62
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cargo
            target
          key: ${{ runner.os }}-stable
      - name: Compiling
        run: cargo build --release
      - name: Running tests
        run: |
          cd libstd
          cargo run --release -p inko -- test
